# DataTypes And Attributes 

In [1]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3.6],[4.2,5.6,6]])
a2

array([[1. , 2. , 3.6],
       [4.2, 5.6, 6. ]])

In [8]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
a1.size

3

In [11]:
a2.size

6

In [12]:
a3.size

12

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 2, 3)

In [16]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [17]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

# Creating Arrays
Different ways of creating arrays

In [19]:
sample_array1 = np.array([4,5,6])
sample_array1

array([4, 5, 6])

In [20]:
ones = np.ones((2,5))

In [21]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
zeros = np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
type(ones),type(zeros)

(numpy.ndarray, numpy.ndarray)

In [26]:
ones.dtype,zeros.dtype

(dtype('float64'), dtype('float64'))

In [29]:
sample_array2 = np.random.randint(2,20, size=(2,3))
sample_array2

array([[15,  9, 11],
       [17, 17,  8]])

In [30]:
sample_array3 = np.arange(0,10,2)
sample_array3

array([0, 2, 4, 6, 8])

In [32]:
sample_array4 = np.random.random((3,2))
sample_array4

array([[0.3047077 , 0.04933344],
       [0.92533683, 0.10354009],
       [0.55824906, 0.93602345]])

In [34]:
sample_array5 = np.random.rand(3,2)

In [35]:
sample_array5

array([[0.33532592, 0.41322114],
       [0.39936975, 0.4872559 ],
       [0.87272524, 0.0266902 ]])

In [36]:
#Creating dataframe from arrays

In [37]:
a2

array([[1. , 2. , 3.6],
       [4.2, 5.6, 6. ]])

In [38]:
import pandas as pd

In [39]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.6
1  4.2  5.6  6.0