In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

E:\Anaconda 3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
from sklearn.datasets import load_boston
boston = load_boston()

In [5]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [6]:
boston_df = pd.DataFrame(boston['data'], columns = boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

# Fit the model

## Clasification model

In [7]:
from sklearn.ensemble import RandomForestClassifier

X = heart_disease.drop('target', axis = 1)
y = heart_disease['target']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

model_1 = RandomForestClassifier()

##Fitting the model
model_1.fit(X_train,y_train)

model_1.score(X_test,y_test)

0.8688524590163934

## Regression Model

In [9]:
from sklearn.ensemble import RandomForestRegressor

X = boston_df.drop('target',axis = 1)
y = boston_df['target']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

model_2 = RandomForestRegressor()

##Fitting the model
model_2.fit(X_train,y_train)

model_2.score(X_test,y_test)

0.8127123914802854

# Making Predictions

## Classification Model

* using 'predict'
* using 'predict_proba'

In [11]:
model_1.predict(np.array([1,2,3,4,5])) #This will not work.

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4. 5.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [13]:
from sklearn.ensemble import RandomForestClassifier

X = heart_disease.drop('target', axis = 1)
y = heart_disease['target']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

model_1 = RandomForestClassifier()

##Fitting the model
model_1.fit(X_train,y_train)

model_1.score(X_test,y_test)

0.8524590163934426

In [14]:
model_1.predict(X_test)

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0], dtype=int64)

In [15]:
np.array(y_test)

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [16]:
y_preds = model_1.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [17]:
model_1.score(X_test,y_test)

0.8524590163934426

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

In [20]:
## predict_proba

model_1.predict_proba(X_test[:5])

array([[0.32, 0.68],
       [0.27, 0.73],
       [0.43, 0.57],
       [0.73, 0.27],
       [0.26, 0.74]])

In [21]:
y_preds[:5]

array([1, 1, 1, 0, 1], dtype=int64)

## Regression Model

In [22]:
from sklearn.ensemble import RandomForestRegressor

X = boston_df.drop('target',axis = 1)
y = boston_df['target']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

model_2 = RandomForestRegressor()

##Fitting the model
model_2.fit(X_train,y_train)

model_2.score(X_test,y_test)

0.8493635677396031

In [24]:
model_2.predict(X_test[:5])

array([25.077, 20.691, 24.515, 23.778, 19.867])

In [25]:
np.array(y_test[:5])

array([27.1, 20.8, 36.2, 23.1, 21.5])

In [27]:
from sklearn.metrics import mean_absolute_error

y_preds = model_2.predict(X_test)
mean_absolute_error(y_test, y_preds)

2.283117647058822