In [1]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [10]:
#Creating a Dataframe
weekly_sales = pd.DataFrame(sales_amount , index=['Mon','Tues','Wed','Thurs','Fri'], 
                           columns = ['Silk','Silk Oreo','Bubbly'])
weekly_sales

Silk  Silk Oreo  Bubbly
Mon      12         15       0
Tues      3          3       7
Wed       9         19      18
Thurs     4          6      12
Fri       1          6       7

In [11]:
Prices = np.array([120,150,80])
Prices

array([120, 150,  80])

In [12]:
Prices.shape

(3,)

In [13]:
Chocolate_sales = pd.DataFrame(Prices.reshape(1,3), index=['Price'],
                              columns=['Silk','Silk Oreo','Bubbly'])
Chocolate_sales

Silk  Silk Oreo  Bubbly
Price   120        150      80

In [14]:
Prices.shape,sales_amount.shape

((3,), (5, 3))

In [15]:
Prices = Prices.reshape(1,3)

In [16]:
daily_sales = np.dot(Prices,sales_amount.T)
daily_sales

array([[3690, 1370, 5370, 2340, 1580]])

In [17]:
weekly_sales['Total (Rs)'] = daily_sales.T
weekly_sales

Silk  Silk Oreo  Bubbly  Total (Rs)
Mon      12         15       0        3690
Tues      3          3       7        1370
Wed       9         19      18        5370
Thurs     4          6      12        2340
Fri       1          6       7        1580