In [1]:
import numpy as np

# Comparison Operators

In [2]:
a1 = np.array([1,2,3])

In [3]:
a2 = np.array([[1,2,3],[4,5,6]])

In [16]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [6]:
a1 < a2

array([[False, False, False],
       [ True,  True,  True]])

In [7]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [8]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [9]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [10]:
bool_array.dtype

dtype('bool')

In [11]:
bool_array.ndim,bool_array.shape

(2, (2, 3))

# Sorting Arrays

In [12]:
a1

array([1, 2, 3])

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [18]:
random_array = np.random.randint(20,size=(5,3))

In [19]:
random_array

array([[ 6, 15,  7],
       [ 4, 16,  0],
       [ 0,  4,  9],
       [16, 18,  2],
       [ 6, 11,  9]])

In [20]:
np.sort(random_array)

array([[ 6,  7, 15],
       [ 0,  4, 16],
       [ 0,  4,  9],
       [ 2, 16, 18],
       [ 6,  9, 11]])

In [23]:
random_array

array([[ 6, 15,  7],
       [ 4, 16,  0],
       [ 0,  4,  9],
       [16, 18,  2],
       [ 6, 11,  9]])

In [21]:
np.sort(random_array,axis = 0)

array([[ 0,  4,  0],
       [ 4, 11,  2],
       [ 6, 15,  7],
       [ 6, 16,  9],
       [16, 18,  9]])

In [22]:
np.sort(random_array,axis = 1)

array([[ 6,  7, 15],
       [ 0,  4, 16],
       [ 0,  4,  9],
       [ 2, 16, 18],
       [ 6,  9, 11]])

In [24]:
random_array

array([[ 6, 15,  7],
       [ 4, 16,  0],
       [ 0,  4,  9],
       [16, 18,  2],
       [ 6, 11,  9]])

In [25]:
np.argsort(random_array)           #sort index

array([[0, 2, 1],
       [2, 0, 1],
       [0, 1, 2],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [26]:
np.argsort(random_array, axis=0)

array([[2, 2, 1],
       [1, 4, 3],
       [0, 0, 0],
       [4, 1, 2],
       [3, 3, 4]], dtype=int64)

In [27]:
from matplotlib.image import imread

<img src = 'car.png'/>

In [32]:
car = imread('car.png')

In [33]:
type(car)

numpy.ndarray

In [34]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [35]:
car.size,car.shape

(991300, (431, 575, 4))

<img src = 'panda.png'/>

In [36]:
panda = imread('panda.png')

In [37]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [38]:
panda.size

24465000

In [39]:
panda.shape

(2330, 3500, 3)

In [40]:
panda.ndim

3

<img src = 'dog.png'/>

In [41]:
dog = imread('dog.png')

In [42]:
type(dog)

numpy.ndarray

In [43]:
dog.ndim

3

In [44]:
dog.shape

(432, 575, 4)

In [45]:
dog.size

993600